### ISSUE TITLE
Advice on stateful processing to build a vocabulary dictionary

### ISSUE THREAD

**Issue by sayakpaul** [chishankar-work/cloud-dataflow-examples#1]
Hi @chishankar-work. Thanks for this example!

I wanted to ask for suggestions on a use case that I am currently working on. I am presenting a minimal example here for convenience:

```python
sample = (
        pipeline
        | 'Create produce' >> beam.Create([
            'I have a bat.',
            I need a racket.',
            'I play football.',
            'We should play basketball as well.',
            'Rondalo is a great athlete.',
        ])
)
```

Say I have the above elements in my pipeline. Now, I would like to build a set that contains all the unique words present here. Could you provide some hints on how should I go about it?

**Comment by chishankar-work** [comment]
Hey @sayakpaul , please see the [WordCount Example](https://github.com/apache/beam/blob/master/sdks/python/apache_beam/examples/wordcount_minimal.py). It has three steps:

1. `Split` -> Uses FlatMap w/ Regex to split all the values
2. `PairWithOne` -> Which then produces one output value for each input value, in this case the word:word_count
3. `GroupSum` -> Step 2, `PairWithOne`, outputs a (K,V) pair. Which in this case, each word would be a key. This step now uses a combinePerKey(sum), which then takes the output value per key across all the intermediate steps, and adds them together to give you an output. 

Hope this helps - thanks!

**Comment by sayakpaul** [comment]
Thank you! Will try this out.
